### ISSUE TITLE
Run Boba/BobaBase in Docker Locally

### ISSUE THREAD

**Issue by excalq** [Partavate-Studios/orbiter8-multiverse-bobabeam#7]
This is recommended in the Dev Docs.
It would allow us to have a faster demo at the Hackathon.
This would bypass required NFT whitelisting with NFT Bridges (requires Boba team actions)

Steps: (From https://docs.boba.network/for-developers/local-stack)
1. Clone Boba's repo run locally: `git clone git@github.com:bobanetwork/boba.git .`
2. Build project tooling: `yarn && yarn build`
3. Build Docker containers: `cd ops/ && BUILD=1 DAEMON=0 ./up_local.sh`
4. Wait for local chain init: `./scripts/wait-for-sequencer.sh`
5. Wait for Contracts Deployment:  `./scripts/wait-for-boba.sh`

**This is where it breaks**:
During `up-local.sh`, the container `ops_boba_deployer_1` dies with these errors:
```
{
  "error": "ERROR processing /opt/optimism/packages/boba/contracts/deploy/004-L2ERC20.deploy.ts:\nError: cannot estimate gas; transaction may fail or may require manual gas limit (error={\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":672,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"execution reverted: Token Address Already Registered\\\"}}\\n\",\"error\":{\"code\":-32000},\"requestBody\":\"{\\\"method\\\":\\\"eth_estimateGas\\\",\\\"params\\\":[{\\\"gasPrice\\\":\\\"0x3b9aca00\\\",\\\"from\\\":\\\"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\\\",\\\"to\\\":\\\"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512\\\",\\\"data\\\":\\\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\\\"}],\\\"id\\\":672,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"http://l2geth:8545\"},\"method\":\"estimateGas\",\"transaction\":{\"from\":\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\",\"gasPrice\":{\"type\":\"BigNumber\",\"hex\":\"0x3b9aca00\"},\"to\":\"0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512\",\"data\":\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\",\"accessList\":null}}, tx={\"data\":\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\",\"to\":{},\"from\":\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\",\"gasPrice\":{\"type\":\"BigNumber\",\"hex\":\"0x3b9aca00\"},\"type\":0,\"nonce\":{},\"gasLimit\":{},\"chainId\":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at /opt/optimism/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 6)",
  "stack": "Error: ERROR processing /opt/optimism/packages/boba/contracts/deploy/004-L2ERC20.deploy.ts:\nError: cannot estimate gas; transaction may fail or may require manual gas limit (error={\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":672,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"execution reverted: Token Address Already Registered\\\"}}\\n\",\"error\":{\"code\":-32000},\"requestBody\":\"{\\\"method\\\":\\\"eth_estimateGas\\\",\\\"params\\\":[{\\\"gasPrice\\\":\\\"0x3b9aca00\\\",\\\"from\\\":\\\"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\\\",\\\"to\\\":\\\"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512\\\",\\\"data\\\":\\\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\\\"}],\\\"id\\\":672,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"http://l2geth:8545\"},\"method\":\"estimateGas\",\"transaction\":{\"from\":\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\",\"gasPrice\":{\"type\":\"BigNumber\",\"hex\":\"0x3b9aca00\"},\"to\":\"0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512\",\"data\":\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\",\"accessList\":null}}, tx={\"data\":\"0x7286e5e50000000000000000000000001613beb3b2c4f22ee086b2b38c1476a3ce7f78e80000000000000000000000004200000000000000000000000000000000000023\",\"to\":{},\"from\":\"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\",\"gasPrice\":{\"type\":\"BigNumber\",\"hex\":\"0x3b9aca00\"},\"type\":0,\"nonce\":{},\"gasLimit\":{},\"chainId\":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at /opt/optimism/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 6)\n    at DeploymentsManager.executeDeployScripts (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async DeploymentsManager.runDeploy (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:409:5)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:555:32)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)"
}
error Command failed with exit code 1.
```

**Comment by excalq** [comment]
This isn't strictly needed for the hackathon. I'll leave it open.
